name: poly_inside_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  drift: ^2.20.0
  sqlite3: ^2.4.6
  grpc: ^4.0.1
  protobuf: ^3.1.0
  l: ^4.0.2
  crypto: ^3.0.5
  schedules: ^0.0.5
  http: ^1.2.2
  html: ^0.15.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.20.1
  lints: ^4.0.0
  test: ^1.25.8
