Map<String, RegExp> alphabet = {
  'а' :   RegExp('[@|а|а́|a]'),
    'б' :   RegExp('[б|6|b]'),
    'в' :   RegExp('[в|b|v]'),
    'г' :   RegExp('[г|r|g]'),
    'д' :   RegExp('[д|d]'),
    'е' :   RegExp('[е|e|ё]'),
    'ж' :   RegExp('[ж|z|*]'),
    'з' :   RegExp('[з|3|z]'),
    'и' :   RegExp('[и|u|i]'),
    'й' :   RegExp('[й|u|i]'),
    'к' :   RegExp('[к|k]'),
    'л' :   RegExp('[л|l]'),
    'м' :   RegExp('[м|m]'),
    'н' :   RegExp('[н|h|n]'),
    'о' :   RegExp('[о|o|0]'),
    'п' :   RegExp('[п|n|p]'),
    'р' :   RegExp('[р|r|p]'),
    'с' :   RegExp(r'[с|c|s|5|$]'),
    'т' :   RegExp('[т|m|t]'),
    'у' :   RegExp('[у́|у|y|u]'),
    'ф' :   RegExp('[ф|f]'),
    'х' :   RegExp('[х|x|h]'),
    'ц' :   RegExp('[ц|c|u]'),
    'ч' :   RegExp('[ч|c|h]'),
    'ш' :   RegExp('[ш|щ]'),
    'ь' :   RegExp('[ь|b]'),
    'ы' :   RegExp('[ы|i]'),
    'ъ' :   RegExp('[ъ|ь]'),
    'э' :   RegExp('[э|e]'),
    'ю' :   RegExp('[ю|y|u]'),
    'я' :   RegExp('[я|r]'),
    ' ' : RegExp('[.|,|!|?|&|)|(|\\|\/|*|-|_|"|\'|;|®]')
};